//! DO NOT EDIT
//! This file is automatically generated by the varlink rust generator

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use error_chain::ChainedError;
use serde_json::{self, Value};
use std::io;
use std::sync::{Arc, RwLock};
use varlink;
use varlink::CallTrait;

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Interface {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub foo: Option<Vec<Option<varlink::StringHashMap<Interface_foo>>>>,
    pub anon: Interface_anon,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct MyType {
    pub object: Value,
    #[serde(rename = "enum")]
    pub enum_: MyType_enum,
    #[serde(rename = "struct")]
    pub struct_: MyType_struct,
    pub array: Vec<String>,
    pub dictionary: varlink::StringHashMap<String>,
    pub stringset: varlink::StringHashSet,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nullable: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nullable_array_struct: Option<Vec<MyType_nullable_array_struct>>,
    pub interface: Interface,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct EndReply_ {
    pub all_ok: bool,
}

impl varlink::VarlinkReply for EndReply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct EndArgs_ {
    pub client_id: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct StartReply_ {
    pub client_id: String,
}

impl varlink::VarlinkReply for StartReply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct StartArgs_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test01Reply_ {
    pub bool: bool,
}

impl varlink::VarlinkReply for Test01Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test01Args_ {
    pub client_id: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test02Reply_ {
    pub int: i64,
}

impl varlink::VarlinkReply for Test02Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test02Args_ {
    pub client_id: String,
    pub bool: bool,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test03Reply_ {
    pub float: f64,
}

impl varlink::VarlinkReply for Test03Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test03Args_ {
    pub client_id: String,
    pub int: i64,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test04Reply_ {
    pub string: String,
}

impl varlink::VarlinkReply for Test04Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test04Args_ {
    pub client_id: String,
    pub float: f64,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test05Reply_ {
    pub bool: bool,
    pub int: i64,
    pub float: f64,
    pub string: String,
}

impl varlink::VarlinkReply for Test05Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test05Args_ {
    pub client_id: String,
    pub string: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test06Reply_ {
    #[serde(rename = "struct")]
    pub struct_: Test06Reply_struct,
}

impl varlink::VarlinkReply for Test06Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test06Args_ {
    pub client_id: String,
    pub bool: bool,
    pub int: i64,
    pub float: f64,
    pub string: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test07Reply_ {
    pub map: varlink::StringHashMap<String>,
}

impl varlink::VarlinkReply for Test07Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test07Args_ {
    pub client_id: String,
    #[serde(rename = "struct")]
    pub struct_: Test07Args_struct,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test08Reply_ {
    pub set: varlink::StringHashSet,
}

impl varlink::VarlinkReply for Test08Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test08Args_ {
    pub client_id: String,
    pub map: varlink::StringHashMap<String>,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test09Reply_ {
    pub mytype: MyType,
}

impl varlink::VarlinkReply for Test09Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test09Args_ {
    pub client_id: String,
    pub set: varlink::StringHashSet,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test10Reply_ {
    pub string: String,
}

impl varlink::VarlinkReply for Test10Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test10Args_ {
    pub client_id: String,
    pub mytype: MyType,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test11Reply_ {}

impl varlink::VarlinkReply for Test11Reply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test11Args_ {
    pub client_id: String,
    pub last_more_replies: Vec<String>,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct CertificationErrorArgs_ {
    pub wants: Value,
    pub got: Value,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct ClientIdErrorArgs_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Interface_anon {
    pub foo: bool,
    pub bar: bool,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct MyType_struct {
    pub first: i64,
    pub second: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct MyType_nullable_array_struct {
    pub first: i64,
    pub second: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test06Reply_struct {
    pub bool: bool,
    pub int: i64,
    pub float: f64,
    pub string: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Test07Args_struct {
    pub bool: bool,
    pub int: i64,
    pub float: f64,
    pub string: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub enum Interface_foo {
    foo,
    bar,
    baz,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub enum MyType_enum {
    one,
    two,
    three,
}

pub trait _CallErr: varlink::CallTrait {
    fn reply_certification_error(&mut self, wants: Value, got: Value) -> Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.varlink.certification.CertificationError".into(),
            Some(serde_json::to_value(CertificationErrorArgs_ { wants, got }).unwrap()),
        )).map_err(|e| e.into())
    }
    fn reply_client_id_error(&mut self) -> Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.varlink.certification.ClientIdError".into(),
            None,
        )).map_err(|e| e.into())
    }
}

impl<'a> _CallErr for varlink::Call<'a> {}

error_chain! {
    errors {
        CertificationError(t: Option<CertificationErrorArgs_>) {
            display("CertificationError: '{:?}'", t)
        }
        ClientIdError(t: Option<ClientIdErrorArgs_>) {
            display("ClientIdError: '{:?}'", t)
        }
    }
    foreign_links {
        Io(::std::io::Error);
        Fmt(::std::fmt::Error);
        SerdeJson(::serde_json::Error);
        }
    links {
        Varlink(::varlink::Error, ::varlink::ErrorKind);
    }
}

impl From<varlink::Reply> for Error {
    fn from(e: varlink::Reply) -> Self {
        if varlink::Error::is_error(&e) {
            return varlink::Error::from(e).into();
        }

        match e {
            varlink::Reply {
                error: Some(ref t), ..
            } if t == "org.varlink.certification.CertificationError" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p) {
                        Ok(v) => ErrorKind::CertificationError(v).into(),
                        Err(_) => ErrorKind::CertificationError(None).into(),
                    },
                    _ => ErrorKind::CertificationError(None).into(),
                }
            }
            varlink::Reply {
                error: Some(ref t), ..
            } if t == "org.varlink.certification.ClientIdError" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p) {
                        Ok(v) => ErrorKind::ClientIdError(v).into(),
                        Err(_) => ErrorKind::ClientIdError(None).into(),
                    },
                    _ => ErrorKind::ClientIdError(None).into(),
                }
            }
            _ => return varlink::Error::from(varlink::ErrorKind::UnknownError(e)).into(),
        }
    }
}

#[derive(Serialize)]
struct internal_error {
    message: String,
}

impl From<Error> for varlink::Error {
    fn from(e: Error) -> Self {
        match e {
            Error(ErrorKind::CertificationError(t), _) => {
                varlink::Error::from(varlink::ErrorKind::UnknownError(varlink::Reply {
                    error: Some("org.varlink.certification.CertificationError".into()),
                    parameters: Some(serde_json::to_value(t).unwrap()),
                    ..Default::default()
                }))
            }
            Error(ErrorKind::ClientIdError(t), _) => {
                varlink::Error::from(varlink::ErrorKind::UnknownError(varlink::Reply {
                    error: Some("org.varlink.certification.ClientIdError".into()),
                    parameters: Some(serde_json::to_value(t).unwrap()),
                    ..Default::default()
                }))
            }
            e => varlink::Error::from(varlink::ErrorKind::UnknownError(varlink::Reply {
                error: Some("org.example.more.InternalError".into()),
                parameters: Some(
                    serde_json::to_value(internal_error {
                        message: e.display_chain().to_string(),
                    }).unwrap(),
                ),
                ..Default::default()
            })),
        }
    }
}
pub trait _CallEnd: _CallErr {
    fn reply(&mut self, all_ok: bool) -> Result<()> {
        self.reply_struct(EndReply_ { all_ok }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallEnd for varlink::Call<'a> {}

pub trait _CallStart: _CallErr {
    fn reply(&mut self, client_id: String) -> Result<()> {
        self.reply_struct(StartReply_ { client_id }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallStart for varlink::Call<'a> {}

pub trait _CallTest01: _CallErr {
    fn reply(&mut self, bool: bool) -> Result<()> {
        self.reply_struct(Test01Reply_ { bool }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest01 for varlink::Call<'a> {}

pub trait _CallTest02: _CallErr {
    fn reply(&mut self, int: i64) -> Result<()> {
        self.reply_struct(Test02Reply_ { int }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest02 for varlink::Call<'a> {}

pub trait _CallTest03: _CallErr {
    fn reply(&mut self, float: f64) -> Result<()> {
        self.reply_struct(Test03Reply_ { float }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest03 for varlink::Call<'a> {}

pub trait _CallTest04: _CallErr {
    fn reply(&mut self, string: String) -> Result<()> {
        self.reply_struct(Test04Reply_ { string }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest04 for varlink::Call<'a> {}

pub trait _CallTest05: _CallErr {
    fn reply(&mut self, bool: bool, int: i64, float: f64, string: String) -> Result<()> {
        self.reply_struct(
            Test05Reply_ {
                bool,
                int,
                float,
                string,
            }.into(),
        ).map_err(|e| e.into())
    }
}

impl<'a> _CallTest05 for varlink::Call<'a> {}

pub trait _CallTest06: _CallErr {
    fn reply(&mut self, struct_: Test06Reply_struct) -> Result<()> {
        self.reply_struct(Test06Reply_ { struct_ }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest06 for varlink::Call<'a> {}

pub trait _CallTest07: _CallErr {
    fn reply(&mut self, map: varlink::StringHashMap<String>) -> Result<()> {
        self.reply_struct(Test07Reply_ { map }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest07 for varlink::Call<'a> {}

pub trait _CallTest08: _CallErr {
    fn reply(&mut self, set: varlink::StringHashSet) -> Result<()> {
        self.reply_struct(Test08Reply_ { set }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest08 for varlink::Call<'a> {}

pub trait _CallTest09: _CallErr {
    fn reply(&mut self, mytype: MyType) -> Result<()> {
        self.reply_struct(Test09Reply_ { mytype }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest09 for varlink::Call<'a> {}

pub trait _CallTest10: _CallErr {
    fn reply(&mut self, string: String) -> Result<()> {
        self.reply_struct(Test10Reply_ { string }.into())
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest10 for varlink::Call<'a> {}

pub trait _CallTest11: _CallErr {
    fn reply(&mut self) -> Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
            .map_err(|e| e.into())
    }
}

impl<'a> _CallTest11 for varlink::Call<'a> {}

pub trait VarlinkInterface {
    fn end(&self, call: &mut _CallEnd, client_id: String) -> Result<()>;
    fn start(&self, call: &mut _CallStart) -> Result<()>;
    fn test01(&self, call: &mut _CallTest01, client_id: String) -> Result<()>;
    fn test02(&self, call: &mut _CallTest02, client_id: String, bool: bool) -> Result<()>;
    fn test03(&self, call: &mut _CallTest03, client_id: String, int: i64) -> Result<()>;
    fn test04(&self, call: &mut _CallTest04, client_id: String, float: f64) -> Result<()>;
    fn test05(&self, call: &mut _CallTest05, client_id: String, string: String) -> Result<()>;
    fn test06(
        &self,
        call: &mut _CallTest06,
        client_id: String,
        bool: bool,
        int: i64,
        float: f64,
        string: String,
    ) -> Result<()>;
    fn test07(
        &self,
        call: &mut _CallTest07,
        client_id: String,
        struct_: Test07Args_struct,
    ) -> Result<()>;
    fn test08(
        &self,
        call: &mut _CallTest08,
        client_id: String,
        map: varlink::StringHashMap<String>,
    ) -> Result<()>;
    fn test09(
        &self,
        call: &mut _CallTest09,
        client_id: String,
        set: varlink::StringHashSet,
    ) -> Result<()>;
    fn test10(&self, call: &mut _CallTest10, client_id: String, mytype: MyType) -> Result<()>;
    fn test11(
        &self,
        call: &mut _CallTest11,
        client_id: String,
        last_more_replies: Vec<String>,
    ) -> Result<()>;
    fn call_upgraded(&self, _call: &mut varlink::Call) -> varlink::Result<()> {
        Ok(())
    }
}

pub trait VarlinkClientInterface {
    fn end(&mut self, client_id: String) -> varlink::MethodCall<EndArgs_, EndReply_, Error>;
    fn start(&mut self) -> varlink::MethodCall<StartArgs_, StartReply_, Error>;
    fn test01(
        &mut self,
        client_id: String,
    ) -> varlink::MethodCall<Test01Args_, Test01Reply_, Error>;
    fn test02(
        &mut self,
        client_id: String,
        bool: bool,
    ) -> varlink::MethodCall<Test02Args_, Test02Reply_, Error>;
    fn test03(
        &mut self,
        client_id: String,
        int: i64,
    ) -> varlink::MethodCall<Test03Args_, Test03Reply_, Error>;
    fn test04(
        &mut self,
        client_id: String,
        float: f64,
    ) -> varlink::MethodCall<Test04Args_, Test04Reply_, Error>;
    fn test05(
        &mut self,
        client_id: String,
        string: String,
    ) -> varlink::MethodCall<Test05Args_, Test05Reply_, Error>;
    fn test06(
        &mut self,
        client_id: String,
        bool: bool,
        int: i64,
        float: f64,
        string: String,
    ) -> varlink::MethodCall<Test06Args_, Test06Reply_, Error>;
    fn test07(
        &mut self,
        client_id: String,
        struct_: Test07Args_struct,
    ) -> varlink::MethodCall<Test07Args_, Test07Reply_, Error>;
    fn test08(
        &mut self,
        client_id: String,
        map: varlink::StringHashMap<String>,
    ) -> varlink::MethodCall<Test08Args_, Test08Reply_, Error>;
    fn test09(
        &mut self,
        client_id: String,
        set: varlink::StringHashSet,
    ) -> varlink::MethodCall<Test09Args_, Test09Reply_, Error>;
    fn test10(
        &mut self,
        client_id: String,
        mytype: MyType,
    ) -> varlink::MethodCall<Test10Args_, Test10Reply_, Error>;
    fn test11(
        &mut self,
        client_id: String,
        last_more_replies: Vec<String>,
    ) -> varlink::MethodCall<Test11Args_, Test11Reply_, Error>;
}

pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
    more: bool,
    oneway: bool,
}

impl VarlinkClient {
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient {
            connection,
            more: false,
            oneway: false,
        }
    }
    pub fn more(&self) -> Self {
        VarlinkClient {
            connection: self.connection.clone(),
            more: true,
            oneway: false,
        }
    }
    pub fn oneway(&self) -> Self {
        VarlinkClient {
            connection: self.connection.clone(),
            more: false,
            oneway: true,
        }
    }
}

impl VarlinkClientInterface for VarlinkClient {
    fn end(&mut self, client_id: String) -> varlink::MethodCall<EndArgs_, EndReply_, Error> {
        varlink::MethodCall::<EndArgs_, EndReply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.End".into(),
            EndArgs_ { client_id },
        )
    }
    fn start(&mut self) -> varlink::MethodCall<StartArgs_, StartReply_, Error> {
        varlink::MethodCall::<StartArgs_, StartReply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Start".into(),
            StartArgs_ {},
        )
    }
    fn test01(
        &mut self,
        client_id: String,
    ) -> varlink::MethodCall<Test01Args_, Test01Reply_, Error> {
        varlink::MethodCall::<Test01Args_, Test01Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test01".into(),
            Test01Args_ { client_id },
        )
    }
    fn test02(
        &mut self,
        client_id: String,
        bool: bool,
    ) -> varlink::MethodCall<Test02Args_, Test02Reply_, Error> {
        varlink::MethodCall::<Test02Args_, Test02Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test02".into(),
            Test02Args_ { client_id, bool },
        )
    }
    fn test03(
        &mut self,
        client_id: String,
        int: i64,
    ) -> varlink::MethodCall<Test03Args_, Test03Reply_, Error> {
        varlink::MethodCall::<Test03Args_, Test03Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test03".into(),
            Test03Args_ { client_id, int },
        )
    }
    fn test04(
        &mut self,
        client_id: String,
        float: f64,
    ) -> varlink::MethodCall<Test04Args_, Test04Reply_, Error> {
        varlink::MethodCall::<Test04Args_, Test04Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test04".into(),
            Test04Args_ { client_id, float },
        )
    }
    fn test05(
        &mut self,
        client_id: String,
        string: String,
    ) -> varlink::MethodCall<Test05Args_, Test05Reply_, Error> {
        varlink::MethodCall::<Test05Args_, Test05Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test05".into(),
            Test05Args_ { client_id, string },
        )
    }
    fn test06(
        &mut self,
        client_id: String,
        bool: bool,
        int: i64,
        float: f64,
        string: String,
    ) -> varlink::MethodCall<Test06Args_, Test06Reply_, Error> {
        varlink::MethodCall::<Test06Args_, Test06Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test06".into(),
            Test06Args_ {
                client_id,
                bool,
                int,
                float,
                string,
            },
        )
    }
    fn test07(
        &mut self,
        client_id: String,
        struct_: Test07Args_struct,
    ) -> varlink::MethodCall<Test07Args_, Test07Reply_, Error> {
        varlink::MethodCall::<Test07Args_, Test07Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test07".into(),
            Test07Args_ { client_id, struct_ },
        )
    }
    fn test08(
        &mut self,
        client_id: String,
        map: varlink::StringHashMap<String>,
    ) -> varlink::MethodCall<Test08Args_, Test08Reply_, Error> {
        varlink::MethodCall::<Test08Args_, Test08Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test08".into(),
            Test08Args_ { client_id, map },
        )
    }
    fn test09(
        &mut self,
        client_id: String,
        set: varlink::StringHashSet,
    ) -> varlink::MethodCall<Test09Args_, Test09Reply_, Error> {
        varlink::MethodCall::<Test09Args_, Test09Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test09".into(),
            Test09Args_ { client_id, set },
        )
    }
    fn test10(
        &mut self,
        client_id: String,
        mytype: MyType,
    ) -> varlink::MethodCall<Test10Args_, Test10Reply_, Error> {
        varlink::MethodCall::<Test10Args_, Test10Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test10".into(),
            Test10Args_ { client_id, mytype },
        )
    }
    fn test11(
        &mut self,
        client_id: String,
        last_more_replies: Vec<String>,
    ) -> varlink::MethodCall<Test11Args_, Test11Reply_, Error> {
        varlink::MethodCall::<Test11Args_, Test11Reply_, Error>::new(
            self.connection.clone(),
            "org.varlink.certification.Test11".into(),
            Test11Args_ {
                client_id,
                last_more_replies,
            },
        )
    }
}

pub struct _InterfaceProxy {
    inner: Box<VarlinkInterface + Send + Sync>,
}

pub fn new(inner: Box<VarlinkInterface + Send + Sync>) -> _InterfaceProxy {
    _InterfaceProxy { inner }
}

impl varlink::Interface for _InterfaceProxy {
    fn get_description(&self) -> &'static str {
        r#####################################"# Interface to test varlink implementations against.
# First you write a varlink client calling:
# Start, Test01, Test02, …, Test09, End
# The return value of the previous call should be the argument of the next call.
# Then you test this client against well known servers like python or rust from
# https://github.com/varlink/
#
# Next you write a varlink server providing the same service as the well known ones.
# Now run your client against it and run well known clients like python or rust
# from https://github.com/varlink/ against your server. If all works out, then
# your new language bindings should be varlink certified.
interface org.varlink.certification

type Interface (
  foo: ?[]?[string](foo, bar, baz),
  anon: (foo: bool, bar: bool)
)

type MyType (
  object: object,
  enum: (one, two, three),
  struct: (first: int, second: string),
  array: []string,
  dictionary: [string]string,
  stringset: [string](),
  nullable: ?string,
  nullable_array_struct: ?[](first: int, second: string),
  interface: Interface
)

method Start() -> (client_id: string)

method Test01(client_id: string) -> (bool: bool)

method Test02(client_id: string, bool: bool) -> (int: int)

method Test03(client_id: string, int: int) -> (float: float)

method Test04(client_id: string, float: float) -> (string: string)

method Test05(client_id: string, string: string) -> (
  bool: bool,
  int: int,
  float: float,
  string: string
)

method Test06(
  client_id: string,
  bool: bool,
  int: int,
  float: float,
  string: string
) -> (
  struct: (
    bool: bool,
    int: int,
    float: float,
    string: string
  )
)

method Test07(
  client_id: string,
  struct: (
    bool: bool,
    int: int,
    float: float,
    string: string
  )
) -> (map: [string]string)

method Test08(client_id: string, map: [string]string) -> (set: [string]())

method Test09(client_id: string, set: [string]()) -> (mytype: MyType)

# returns more than one reply with "continues"
method Test10(client_id: string, mytype: MyType) -> (string: string)

# must be called as "oneway"
method Test11(client_id: string, last_more_replies: []string) -> ()

method End(client_id: string) -> (all_ok: bool)

error ClientIdError ()
error CertificationError (wants: object, got: object)
"#####################################
    }

    fn get_name(&self) -> &'static str {
        "org.varlink.certification"
    }

    fn call_upgraded(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        self.inner.call_upgraded(call)
    }

    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "org.varlink.certification.End" => {
                if let Some(args) = req.parameters.clone() {
                    let args: EndArgs_ = serde_json::from_value(args)?;
                    return self.inner
                        .end(call as &mut _CallEnd, args.client_id)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Start" => {
                return self.inner
                    .start(call as &mut _CallStart)
                    .map_err(|e| e.into());
            }
            "org.varlink.certification.Test01" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test01Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test01(call as &mut _CallTest01, args.client_id)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test02" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test02Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test02(call as &mut _CallTest02, args.client_id, args.bool)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test03" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test03Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test03(call as &mut _CallTest03, args.client_id, args.int)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test04" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test04Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test04(call as &mut _CallTest04, args.client_id, args.float)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test05" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test05Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test05(call as &mut _CallTest05, args.client_id, args.string)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test06" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test06Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test06(
                            call as &mut _CallTest06,
                            args.client_id,
                            args.bool,
                            args.int,
                            args.float,
                            args.string,
                        )
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test07" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test07Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test07(call as &mut _CallTest07, args.client_id, args.struct_)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test08" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test08Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test08(call as &mut _CallTest08, args.client_id, args.map)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test09" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test09Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test09(call as &mut _CallTest09, args.client_id, args.set)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test10" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test10Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test10(call as &mut _CallTest10, args.client_id, args.mytype)
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "org.varlink.certification.Test11" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Test11Args_ = serde_json::from_value(args)?;
                    return self.inner
                        .test11(
                            call as &mut _CallTest11,
                            args.client_id,
                            args.last_more_replies,
                        )
                        .map_err(|e| e.into());
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }

            m => {
                return call.reply_method_not_found(String::from(m));
            }
        }
    }
}
