// This file is automatically generated by the varlink rust generator
use std::io;

use varlink;
use serde_json;

#[derive(Serialize, Deserialize, Debug)]
pub struct Netdev {
    pub ifindex: Option<i64>,
    pub ifname: Option<String>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct NetdevInfo {
    pub ifindex: Option<i64>,
    pub ifname: Option<String>,
}


#[allow(non_camel_case_types)]
#[derive(Serialize, Deserialize, Debug)]
struct Info_Reply {
    info: Option<NetdevInfo>,
}
impl varlink::server::VarlinkReply for Info_Reply {}

#[allow(non_camel_case_types)]
#[derive(Serialize, Deserialize, Debug)]
struct Info_Args {
    ifindex: Option<i64>,
}

#[allow(non_camel_case_types)]
#[derive(Serialize, Deserialize, Debug)]
struct List_Reply {
    netdevs: Option<Vec<Netdev>>,
}
impl varlink::server::VarlinkReply for List_Reply {}

#[allow(non_camel_case_types)]
#[derive(Serialize, Deserialize, Debug)]
struct UnknownError_Args {
    text: Option<String>,
}

#[allow(non_camel_case_types)]
#[derive(Serialize, Deserialize, Debug)]
struct UnknownNetworkIfIndex_Args {
    ifindex: Option<i64>,
}

pub trait Reply {
    fn reply_info(&mut self, info: Option<NetdevInfo>) -> io::Result<()>;
    fn reply_list(&mut self, netdevs: Option<Vec<Netdev>>) -> io::Result<()>;
    fn reply_unknown_error(&mut self, text: Option<String>) -> io::Result<()>;
    fn reply_unknown_network_if_index(&mut self, ifindex: Option<i64>) -> io::Result<()>;
}

impl<'a> Reply for varlink::server::Call<'a> {
    fn reply_info(&mut self, info: Option<NetdevInfo>) -> io::Result<()> {
        self.reply(Info_Reply { info }.into())
    }

    fn reply_list(&mut self, netdevs: Option<Vec<Netdev>>) -> io::Result<()> {
        self.reply(List_Reply { netdevs }.into())
    }

    fn reply_unknown_error(&mut self, text: Option<String>) -> io::Result<()> {
        self.reply(varlink::server::Reply::error("io.systemd.network.UnknownError".into(),
                                                 Some(serde_json::to_value(UnknownError_Args {
                                                                               text,
                                                                           }).unwrap())))
    }

    fn reply_unknown_network_if_index(&mut self, ifindex: Option<i64>) -> io::Result<()> {
        self.reply(varlink::server::Reply::error("io.systemd.network.UnknownNetworkIfIndex".into(),
                                                 Some(serde_json::to_value(UnknownNetworkIfIndex_Args {
                                                                               ifindex,
                                                                           }).unwrap())))
    }
}

pub trait Interface {
    fn info(&self, &mut varlink::server::Call, ifindex: Option<i64>) -> io::Result<()>;
    fn list(&self, &mut varlink::server::Call) -> io::Result<()>;
    fn call_upgraded(&self, &mut varlink::server::Call) -> io::Result<()>;
}

pub struct InterfaceImpl {
    inner: Box<Interface + Send + Sync>,
}

pub fn new(inner: Box<Interface + Send + Sync>) -> InterfaceImpl {
    InterfaceImpl { inner }
}

impl varlink::server::Interface for InterfaceImpl {
    fn get_description(&self) -> &'static str {
        r#"
# Provides information about network state
interface io.systemd.network

type NetdevInfo (
  ifindex: int,
  ifname: string
)

type Netdev (
  ifindex: int,
  ifname: string
)

# Returns information about a network device
method Info(ifindex: int) -> (info: NetdevInfo)

# Lists all network devices
method List() -> (netdevs: Netdev[])

error UnknownNetworkDevice ()
error UnknownError (text: string)
"#
    }

    fn get_name(&self) -> &'static str {
        "io.systemd.network"
    }

    fn call_upgraded(&self, call: &mut varlink::server::Call) -> io::Result<()> {
        self.inner.call_upgraded(call)
    }

    fn call(&self, call: &mut varlink::server::Call) -> io::Result<()> {
        let req = call.request.unwrap();
        let method = req.method.clone();
        match method.as_ref() {
            "io.systemd.network.Info" => {
                if let Some(args) = req.parameters.clone() {
                    let args: Info_Args = serde_json::from_value(args)?;
                    return self.inner.info(call, args.ifindex);
                } else {
                    return call.reply_invalid_parameter(None);
                }
            }
            "io.systemd.network.List" => return self.inner.list(call),
            m => {
                let method: String = m.clone().into();
                return call.reply_method_not_found(Some(method));
            }
        }
    }
}
