[package]
name = "varlink_derive"
version = "9.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink_derive"
repository = "https://github.com/varlink/rust"
description = "Rust code generator macro for the varlink protocol."

[lib]
proc-macro = true
name = "varlink_derive"
path = "src/lib.rs"

[dependencies]
varlink_generator = { version = "9.0", path = "../varlink_generator" }

