# cargo-release configuration
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Disable automatic pushing (you can push manually after review)
push = false

# Tag configuration
tag = true

# Enable publishing to crates.io
publish = true