//! DO NOT EDIT
//! This file is automatically generated by the varlink rust generator

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use serde_json::{self, Value};
use std::io;
use std::sync::{Arc, RwLock};
use varlink;
use varlink::CallTrait;

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Netdev {
    pub ifindex: i64,
    pub ifname: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct NetdevInfo {
    pub ifindex: i64,
    pub ifname: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct InfoReply_ {
    pub info: NetdevInfo,
}

impl varlink::VarlinkReply for InfoReply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct InfoArgs_ {
    pub ifindex: i64,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct ListReply_ {
    pub netdevs: Vec<Netdev>,
}

impl varlink::VarlinkReply for ListReply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct ListArgs_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct UnknownErrorArgs_ {
    pub text: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct UnknownNetworkIfIndexArgs_ {
    pub ifindex: i64,
}

pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_unknown_error(&mut self, text: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "io.systemd.network.UnknownError",
            Some(serde_json::to_value(UnknownErrorArgs_ { text })?),
        ))
    }
    fn reply_unknown_network_if_index(&mut self, ifindex: i64) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "io.systemd.network.UnknownNetworkIfIndex",
            Some(serde_json::to_value(UnknownNetworkIfIndexArgs_ {
                ifindex,
            })?),
        ))
    }
}

impl<'a> VarlinkCallError for varlink::Call<'a> {}

#[derive(Debug)]
pub enum Error {
    UnknownError(Option<UnknownErrorArgs_>),
    UnknownNetworkIfIndex(Option<UnknownNetworkIfIndexArgs_>),
    VarlinkError(varlink::Error),
    UnknownError_(varlink::Reply),
    IOError_(io::Error),
    JSONError_(serde_json::Error),
}

pub type Result<T> = ::std::result::Result<T, Error>;

impl ::std::fmt::Display for Error {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            Error::VarlinkError(e) => e.fmt(fmt),
            Error::JSONError_(e) => e.fmt(fmt),
            Error::IOError_(e) => e.fmt(fmt),
            Error::UnknownError_(varlink::Reply {
                parameters: Some(p),
                ..
            }) => p.fmt(fmt),
            e => write!(fmt, "{:?}", e),
        }
    }
}

impl From<varlink::Reply> for Error {
    fn from(e: varlink::Reply) -> Self {
        if varlink::Error::is_error(&e) {
            return Error::VarlinkError(e.into());
        }

        match e {
            varlink::Reply {
                error: Some(ref t), ..
            } if t == "io.systemd.network.UnknownError" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p) {
                        Ok(v) => Error::UnknownError(v),
                        Err(_) => Error::UnknownError(None),
                    },
                    _ => Error::UnknownError(None),
                }
            }
            varlink::Reply {
                error: Some(ref t), ..
            } if t == "io.systemd.network.UnknownNetworkIfIndex" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p) {
                        Ok(v) => Error::UnknownNetworkIfIndex(v),
                        Err(_) => Error::UnknownNetworkIfIndex(None),
                    },
                    _ => Error::UnknownNetworkIfIndex(None),
                }
            }
            _ => return Error::UnknownError_(e),
        }
    }
}

impl From<io::Error> for Error {
    fn from(e: io::Error) -> Self {
        Error::IOError_(e)
    }
}

impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        Error::VarlinkError(e)
    }
}

impl From<serde_json::Error> for Error {
    fn from(e: serde_json::Error) -> Self {
        use serde_json::error::Category;
        match e.classify() {
            Category::Io => Error::IOError_(e.into()),
            _ => Error::JSONError_(e),
        }
    }
}
pub trait CallInfo_: VarlinkCallError {
    fn reply(&mut self, info: NetdevInfo) -> varlink::Result<()> {
        self.reply_struct(InfoReply_ { info }.into())
    }
}

impl<'a> CallInfo_ for varlink::Call<'a> {}

pub trait CallList_: VarlinkCallError {
    fn reply(&mut self, netdevs: Vec<Netdev>) -> varlink::Result<()> {
        self.reply_struct(ListReply_ { netdevs }.into())
    }
}

impl<'a> CallList_ for varlink::Call<'a> {}

pub trait VarlinkInterface {
    fn info(&self, call: &mut CallInfo_, ifindex: i64) -> varlink::Result<()>;
    fn list(&self, call: &mut CallList_) -> varlink::Result<()>;
    fn call_upgraded(&self, _call: &mut varlink::Call) -> varlink::Result<()> {
        Ok(())
    }
}

pub trait VarlinkClientInterface {
    fn info(&mut self, ifindex: i64) -> varlink::MethodCall<InfoArgs_, InfoReply_, Error>;
    fn list(&mut self) -> varlink::MethodCall<ListArgs_, ListReply_, Error>;
}

pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
    more: bool,
    oneway: bool,
}

impl VarlinkClient {
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient {
            connection,
            more: false,
            oneway: false,
        }
    }
    pub fn more(&self) -> Self {
        VarlinkClient {
            connection: self.connection.clone(),
            more: true,
            oneway: false,
        }
    }
    pub fn oneway(&self) -> Self {
        VarlinkClient {
            connection: self.connection.clone(),
            more: false,
            oneway: true,
        }
    }
}

impl VarlinkClientInterface for VarlinkClient {
    fn info(&mut self, ifindex: i64) -> varlink::MethodCall<InfoArgs_, InfoReply_, Error> {
        varlink::MethodCall::<InfoArgs_, InfoReply_, Error>::new(
            self.connection.clone(),
            "io.systemd.network.Info",
            InfoArgs_ { ifindex },
        )
    }
    fn list(&mut self) -> varlink::MethodCall<ListArgs_, ListReply_, Error> {
        varlink::MethodCall::<ListArgs_, ListReply_, Error>::new(
            self.connection.clone(),
            "io.systemd.network.List",
            ListArgs_ {},
        )
    }
}

pub struct VarlinkInterfaceProxy {
    inner: Box<VarlinkInterface + Send + Sync>,
}

pub fn new(inner: Box<VarlinkInterface + Send + Sync>) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}

impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        r#####################################"# Provides information about network state
#
interface io.systemd.network

type NetdevInfo (
  ifindex: int,
  ifname: string
)

type Netdev (
  ifindex: int,
  ifname: string
)

# Returns information about a network device
method Info(ifindex: int) -> (info: NetdevInfo)

# Lists all network devices
method List() -> (netdevs: []Netdev)

error UnknownNetworkIfIndex (ifindex: int)
error UnknownError (text: string)
"#####################################
    }

    fn get_name(&self) -> &'static str {
        "io.systemd.network"
    }

    fn call_upgraded(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        self.inner.call_upgraded(call)
    }

    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "io.systemd.network.Info" => {
                if let Some(args) = req.parameters.clone() {
                    let args: InfoArgs_ = serde_json::from_value(args)?;
                    return self.inner.info(call as &mut CallInfo_, args.ifindex);
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }
            "io.systemd.network.List" => {
                return self.inner.list(call as &mut CallList_);
            }

            m => {
                return call.reply_method_not_found(String::from(m));
            }
        }
    }
}
