//! DO NOT EDIT
//! This file is automatically generated by the varlink rust generator

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused_imports)]

use serde_json::{self, Value};
use std::io;
use std::sync::{Arc, RwLock};
use varlink;
use varlink::CallTrait;

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct PingReply_ {
    pub pong: String,
}

impl varlink::VarlinkReply for PingReply_ {}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct PingArgs_ {
    pub ping: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct PingErrorArgs_ {
    pub parameter: i64,
}

pub trait CallErr_: varlink::CallTrait {
    fn reply_ping_error(&mut self, parameter: i64) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.example.ping.PingError",
            Some(serde_json::to_value(PingErrorArgs_ { parameter })?),
        ))
    }
}

impl<'a> CallErr_ for varlink::Call<'a> {}

#[derive(Debug)]
pub enum Error {
    PingError(Option<PingErrorArgs_>),
    VarlinkError(varlink::Error),
    UnknownError_(varlink::Reply),
    IOError_(io::Error),
    JSONError_(serde_json::Error),
}

impl From<varlink::Reply> for Error {
    fn from(e: varlink::Reply) -> Self {
        if varlink::Error::is_error(&e) {
            return Error::VarlinkError(e.into());
        }

        match e {
            varlink::Reply {
                error: Some(ref t), ..
            } if t == "org.example.ping.PingError" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p) {
                        Ok(v) => Error::PingError(v),
                        Err(_) => Error::PingError(None),
                    },
                    _ => Error::PingError(None),
                }
            }
            _ => return Error::UnknownError_(e),
        }
    }
}

#[derive(Serialize)]
struct internal_error {
    message: String,
}

pub type Result<T> = ::std::result::Result<T, Error>;

impl ::std::fmt::Display for Error {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            Error::VarlinkError(e) => e.fmt(fmt),
            Error::JSONError_(e) => e.fmt(fmt),
            Error::IOError_(e) => e.fmt(fmt),
            Error::UnknownError_(t) => varlink::Error::from(t.clone()).fmt(fmt),
            e => write!(fmt, "{:?}", e),
        }
    }
}

impl From<io::Error> for Error {
    fn from(e: io::Error) -> Self {
        Error::IOError_(e)
    }
}

impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        Error::VarlinkError(e)
    }
}

impl From<serde_json::Error> for Error {
    fn from(e: serde_json::Error) -> Self {
        use serde_json::error::Category;
        match e.classify() {
            Category::Io => Error::IOError_(e.into()),
            _ => Error::JSONError_(e),
        }
    }
}

impl From<Error> for varlink::Error {
    fn from(e: Error) -> Self {
        match e {
            Error::PingError(t) => {
                varlink::Error::from(varlink::ErrorKind::UnknownError(varlink::Reply {
                    error: Some("org.example.ping.PingError".into()),
                    parameters: serde_json::to_value(t).ok(),
                    ..Default::default()
                }))
            }
            Error::VarlinkError(e) => e,
            Error::JSONError_(t) => varlink::Error::from(t),
            Error::IOError_(t) => varlink::Error::from(t),
            Error::UnknownError_(t) => varlink::Error::from(t),
        }
    }
}
pub trait CallPing_: CallErr_ {
    fn reply(&mut self, pong: String) -> varlink::Result<()> {
        self.reply_struct(PingReply_ { pong }.into())
    }
}

impl<'a> CallPing_ for varlink::Call<'a> {}

pub trait VarlinkInterface {
    fn ping(&self, call: &mut CallPing_, ping: String) -> varlink::Result<()>;
    fn call_upgraded(&self, _call: &mut varlink::Call) -> varlink::Result<()> {
        Ok(())
    }
}

pub trait VarlinkClientInterface {
    fn ping(&mut self, ping: String) -> varlink::MethodCall<PingArgs_, PingReply_, Error>;
}

pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
    more: bool,
    oneway: bool,
}

impl VarlinkClient {
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient {
            connection,
            more: false,
            oneway: false,
        }
    }
    pub fn more(&self) -> Self {
        VarlinkClient {
            connection: self.connection.clone(),
            more: true,
            oneway: false,
        }
    }
    pub fn oneway(&self) -> Self {
        VarlinkClient {
            connection: self.connection.clone(),
            more: false,
            oneway: true,
        }
    }
}

impl VarlinkClientInterface for VarlinkClient {
    fn ping(&mut self, ping: String) -> varlink::MethodCall<PingArgs_, PingReply_, Error> {
        varlink::MethodCall::<PingArgs_, PingReply_, Error>::new(
            self.connection.clone(),
            "org.example.ping.Ping",
            PingArgs_ { ping },
        )
    }
}

pub struct _InterfaceProxy {
    inner: Box<VarlinkInterface + Send + Sync>,
}

pub fn new(inner: Box<VarlinkInterface + Send + Sync>) -> _InterfaceProxy {
    _InterfaceProxy { inner }
}

impl varlink::Interface for _InterfaceProxy {
    fn get_description(&self) -> &'static str {
        r#####################################"# Example service
interface org.example.ping

# Returns the same string
method Ping(ping: string) -> (pong: string)

error PingError(parameter: int)"#####################################
    }

    fn get_name(&self) -> &'static str {
        "org.example.ping"
    }

    fn call_upgraded(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        self.inner.call_upgraded(call)
    }

    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "org.example.ping.Ping" => {
                if let Some(args) = req.parameters.clone() {
                    let args: PingArgs_ = serde_json::from_value(args)?;
                    return self.inner.ping(call as &mut CallPing_, args.ping);
                } else {
                    return call.reply_invalid_parameter("parameters".into());
                }
            }

            m => {
                return call.reply_method_not_found(String::from(m));
            }
        }
    }
}
