#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use async_trait::async_trait;
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::Arc;
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
    TestMoreError(Option<TestMoreError_Args>),
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
            ErrorKind::TestMoreError(v) => write!(f, "org.example.more.TestMoreError: {:#?}", v),
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            varlink::Reply { error: Some(t), .. } if t == "org.example.more.TestMoreError" => {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p.clone()) {
                        Ok(v) => ErrorKind::TestMoreError(v),
                        Err(_) => ErrorKind::TestMoreError(None),
                    },
                    _ => ErrorKind::TestMoreError(None),
                }
            }
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_test_more_error(&mut self, r#reason: String) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.example.more.TestMoreError",
            Some(
                serde_json::to_value(TestMoreError_Args { r#reason })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct r#State {
    pub r#start: Option<bool>,
    pub r#progress: Option<i64>,
    pub r#end: Option<bool>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct TestMoreError_Args {
    pub r#reason: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Ping_Reply {
    pub r#pong: String,
}
impl varlink::VarlinkReply for Ping_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Ping_Args {
    pub r#ping: String,
}
#[allow(dead_code)]
pub trait Call_Ping: VarlinkCallError + Send {
    fn reply(&mut self, r#pong: String) -> varlink::Result<()> {
        self.reply_struct(Ping_Reply { r#pong }.into())
    }
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct StopServing_Reply {}
impl varlink::VarlinkReply for StopServing_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct StopServing_Args {}
#[allow(dead_code)]
pub trait Call_StopServing: VarlinkCallError + Send {
    fn reply(&mut self) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::parameters(None))
    }
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct TestMore_Reply {
    pub r#state: State,
}
impl varlink::VarlinkReply for TestMore_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct TestMore_Args {
    pub r#n: i64,
}
#[allow(dead_code)]
pub trait Call_TestMore: VarlinkCallError + Send {
    fn reply(&mut self, r#state: State) -> varlink::Result<()> {
        self.reply_struct(TestMore_Reply { r#state }.into())
    }
}
#[allow(dead_code)]
#[derive(Default)]
pub struct AsyncCall {
    continues: bool,
    more: bool,
    oneway: bool,
    replies: Vec<varlink::Reply>,
}
impl AsyncCall {
    pub fn new(more: bool, oneway: bool) -> Self {
        AsyncCall {
            continues: false,
            more,
            oneway,
            replies: Vec::new(),
        }
    }
    pub fn take_replies(&mut self) -> Vec<varlink::Reply> {
        std::mem::take(&mut self.replies)
    }
}
impl varlink::CallTrait for AsyncCall {
    fn reply_struct(&mut self, mut reply: varlink::Reply) -> varlink::Result<()> {
        if self.continues {
            if !self.more {
                return Err(varlink::context!(varlink::ErrorKind::CallContinuesMismatch));
            }
            reply.continues = Some(true);
        }
        self.replies.push(reply);
        Ok(())
    }
    fn set_continues(&mut self, cont: bool) {
        self.continues = cont;
    }
    fn to_upgraded(&mut self) {}
    fn is_oneway(&self) -> bool {
        self.oneway
    }
    fn wants_more(&self) -> bool {
        self.more
    }
    fn get_request(&self) -> Option<&varlink::Request<'_>> {
        None
    }
}
impl VarlinkCallError for AsyncCall {}
impl Call_Ping for AsyncCall {}
impl Call_StopServing for AsyncCall {}
impl Call_TestMore for AsyncCall {}
#[async_trait]
#[allow(dead_code)]
pub trait VarlinkInterface {
    async fn ping(&self, call: &mut dyn Call_Ping, r#ping: String) -> varlink::Result<()>;
    async fn stop_serving(&self, call: &mut dyn Call_StopServing) -> varlink::Result<()>;
    async fn test_more(&self, call: &mut dyn Call_TestMore, r#n: i64) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn ping(&self, r#ping: String) -> varlink::AsyncMethodCall<Ping_Args, Ping_Reply, Error>;
    fn stop_serving(&self) -> varlink::AsyncMethodCall<StopServing_Args, StopServing_Reply, Error>;
    fn test_more(&self, r#n: i64)
        -> varlink::AsyncMethodCall<TestMore_Args, TestMore_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<varlink::AsyncConnection>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<varlink::AsyncConnection>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn ping(&self, r#ping: String) -> varlink::AsyncMethodCall<Ping_Args, Ping_Reply, Error> {
        varlink::AsyncMethodCall::<Ping_Args, Ping_Reply, Error>::new(
            self.connection.clone(),
            "org.example.more.Ping",
            Ping_Args { r#ping },
        )
    }
    fn stop_serving(&self) -> varlink::AsyncMethodCall<StopServing_Args, StopServing_Reply, Error> {
        varlink::AsyncMethodCall::<StopServing_Args, StopServing_Reply, Error>::new(
            self.connection.clone(),
            "org.example.more.StopServing",
            StopServing_Args {},
        )
    }
    fn test_more(
        &self,
        r#n: i64,
    ) -> varlink::AsyncMethodCall<TestMore_Args, TestMore_Reply, Error> {
        varlink::AsyncMethodCall::<TestMore_Args, TestMore_Reply, Error>::new(
            self.connection.clone(),
            "org.example.more.TestMore",
            TestMore_Args { r#n },
        )
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceHandler {
    inner: Arc<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Arc<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceHandler {
    VarlinkInterfaceHandler { inner }
}
#[async_trait]
impl varlink::AsyncConnectionHandler for VarlinkInterfaceHandler {
    async fn handle(
        &self,
        server: &mut varlink::sansio::Server,
        _upgraded_iface: Option<String>,
    ) -> varlink::Result<Option<String>> {
        while let Some(event) = server.poll_event() {
            match event {
                varlink::sansio::ServerEvent::Request { request } => {
                    let more = request.more.unwrap_or(false);
                    let oneway = request.oneway.unwrap_or(false);
                    let mut call = AsyncCall::new(more, oneway);
                    match request.method.as_ref() {
                        "org.example.more.Ping" => {
                            if let Some(args) = request.parameters {
                                let args: Ping_Args =
                                    serde_json::from_value(args).map_err(|e| {
                                        varlink::Error(
                                            varlink::ErrorKind::InvalidParameter(e.to_string()),
                                            None,
                                            None,
                                        )
                                    })?;
                                self.inner
                                    .ping(&mut call as &mut dyn Call_Ping, args.r#ping)
                                    .await?;
                            } else {
                                call.reply_invalid_parameter("parameters".into())?;
                            }
                        }
                        "org.example.more.StopServing" => {
                            self.inner
                                .stop_serving(&mut call as &mut dyn Call_StopServing)
                                .await?;
                        }
                        "org.example.more.TestMore" => {
                            if let Some(args) = request.parameters {
                                let args: TestMore_Args =
                                    serde_json::from_value(args).map_err(|e| {
                                        varlink::Error(
                                            varlink::ErrorKind::InvalidParameter(e.to_string()),
                                            None,
                                            None,
                                        )
                                    })?;
                                self.inner
                                    .test_more(&mut call as &mut dyn Call_TestMore, args.r#n)
                                    .await?;
                            } else {
                                call.reply_invalid_parameter("parameters".into())?;
                            }
                        }
                        method => {
                            call.reply_method_not_found(method.to_string())?;
                        }
                    }
                    for reply in call.take_replies() {
                        server.send_reply(reply)?;
                    }
                }
                varlink::sansio::ServerEvent::Upgrade { interface } => {
                    return Ok(Some(interface));
                }
            }
        }
        Ok(None)
    }
}
impl varlink::AsyncInterface for VarlinkInterfaceHandler {
    fn get_name(&self) -> &'static str {
        "org.example.more"
    }
    fn get_description(&self) -> &'static str {
        "# Example Varlink service\ninterface org.example.more\n\n# Enum, returning either start, progress or end\n# progress: [0-100]\ntype State (\n  start: ?bool,\n  progress: ?int,\n  end: ?bool\n)\n\n# Returns the same string\nmethod Ping(ping: string) -> (pong: string)\n\n# Dummy progress method\n# n: number of progress steps\nmethod TestMore(n: int) -> (state: State)\n\n# Stop serving\nmethod StopServing() -> ()\n\n# Something failed in TestMore\nerror TestMoreError (reason: string)\n"
    }
}
