#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use async_trait::async_trait;
use serde_derive::{Deserialize, Serialize};
use std::io::BufRead;
use std::sync::Arc;
use varlink::{self, CallTrait};
#[allow(dead_code)]
#[derive(Clone, PartialEq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
    PingError(Option<PingError_Args>),
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ErrorKind::Varlink_Error => write!(f, "Varlink Error"),
            ErrorKind::VarlinkReply_Error => write!(f, "Varlink error reply"),
            ErrorKind::PingError(v) => write!(f, "org.example.ping.PingError: {:#?}", v),
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    #[allow(dead_code)]
    pub fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Error(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}
#[allow(dead_code)]
pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Error(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Error(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}
#[allow(dead_code)]
impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        match e {
            varlink::Reply { error: Some(t), .. } if t == "org.example.ping.PingError" => match e {
                varlink::Reply {
                    parameters: Some(p),
                    ..
                } => match serde_json::from_value(p.clone()) {
                    Ok(v) => ErrorKind::PingError(v),
                    Err(_) => ErrorKind::PingError(None),
                },
                _ => ErrorKind::PingError(None),
            },
            _ => ErrorKind::VarlinkReply_Error,
        }
    }
}
#[allow(dead_code)]
pub trait VarlinkCallError: varlink::CallTrait {
    fn reply_ping_error(&mut self, r#parameter: i64) -> varlink::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "org.example.ping.PingError",
            Some(
                serde_json::to_value(PingError_Args { r#parameter })
                    .map_err(varlink::map_context!())?,
            ),
        ))
    }
}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct PingError_Args {
    pub r#parameter: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Ping_Reply {
    pub r#pong: String,
}
impl varlink::VarlinkReply for Ping_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct Ping_Args {
    pub r#ping: String,
}
#[allow(dead_code)]
pub trait Call_Ping: VarlinkCallError + Send {
    fn reply(&mut self, r#pong: String) -> varlink::Result<()> {
        self.reply_struct(Ping_Reply { r#pong }.into())
    }
}
#[allow(dead_code)]
#[derive(Default)]
pub struct AsyncCall {
    reply: Option<varlink::Reply>,
}
impl AsyncCall {
    pub fn take_reply(&mut self) -> Option<varlink::Reply> {
        self.reply.take()
    }
}
impl varlink::CallTrait for AsyncCall {
    fn reply_struct(&mut self, reply: varlink::Reply) -> varlink::Result<()> {
        self.reply = Some(reply);
        Ok(())
    }
    fn set_continues(&mut self, _cont: bool) {}
    fn to_upgraded(&mut self) {}
    fn is_oneway(&self) -> bool {
        false
    }
    fn wants_more(&self) -> bool {
        false
    }
    fn get_request(&self) -> Option<&varlink::Request<'_>> {
        None
    }
}
impl VarlinkCallError for AsyncCall {}
impl Call_Ping for AsyncCall {}
#[async_trait]
#[allow(dead_code)]
pub trait VarlinkInterface {
    async fn ping(&self, call: &mut dyn Call_Ping, r#ping: String) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}
#[allow(dead_code)]
pub trait VarlinkClientInterface {
    fn ping(&self, r#ping: String) -> varlink::AsyncMethodCall<Ping_Args, Ping_Reply, Error>;
}
#[allow(dead_code)]
pub struct VarlinkClient {
    connection: Arc<varlink::AsyncConnection>,
}
impl VarlinkClient {
    #[allow(dead_code)]
    pub fn new(connection: Arc<varlink::AsyncConnection>) -> Self {
        VarlinkClient { connection }
    }
}
impl VarlinkClientInterface for VarlinkClient {
    fn ping(&self, r#ping: String) -> varlink::AsyncMethodCall<Ping_Args, Ping_Reply, Error> {
        varlink::AsyncMethodCall::<Ping_Args, Ping_Reply, Error>::new(
            self.connection.clone(),
            "org.example.ping.Ping",
            Ping_Args { r#ping },
        )
    }
}
#[allow(dead_code)]
pub struct VarlinkInterfaceHandler {
    inner: Arc<dyn VarlinkInterface + Send + Sync>,
}
#[allow(dead_code)]
pub fn new(inner: Arc<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceHandler {
    VarlinkInterfaceHandler { inner }
}
#[async_trait]
impl varlink::AsyncConnectionHandler for VarlinkInterfaceHandler {
    async fn handle(
        &self,
        server: &mut varlink::sansio::Server,
        _upgraded_iface: Option<String>,
    ) -> varlink::Result<Option<String>> {
        while let Some(event) = server.poll_event() {
            match event {
                varlink::sansio::ServerEvent::Request { request } => {
                    let mut call = AsyncCall::default();
                    match request.method.as_ref() {
                        "org.example.ping.Ping" => {
                            if let Some(args) = request.parameters {
                                let args: Ping_Args =
                                    serde_json::from_value(args).map_err(|e| {
                                        varlink::Error(
                                            varlink::ErrorKind::InvalidParameter(e.to_string()),
                                            None,
                                            None,
                                        )
                                    })?;
                                self.inner
                                    .ping(&mut call as &mut dyn Call_Ping, args.r#ping)
                                    .await?;
                            } else {
                                call.reply_invalid_parameter("parameters".into())?;
                            }
                        }
                        method => {
                            call.reply_method_not_found(method.to_string())?;
                        }
                    }
                    if let Some(reply) = call.take_reply() {
                        server.send_reply(reply)?;
                    }
                }
                varlink::sansio::ServerEvent::Upgrade { interface } => {
                    return Ok(Some(interface));
                }
            }
        }
        Ok(None)
    }
}
impl varlink::AsyncInterface for VarlinkInterfaceHandler {
    fn get_name(&self) -> &'static str {
        "org.example.ping"
    }
    fn get_description(&self) -> &'static str {
        "# Example async service\ninterface org.example.ping\n\n# Returns the same string\nmethod Ping(ping: string) -> (pong: string)\n\nerror PingError(parameter: int)\n"
    }
}
