//! DO NOT EDIT
//! This file is automatically generated by the varlink rust generator

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use serde_json;
use std::io;
use std::sync::{Arc, RwLock};
use varlink;
use varlink::CallTrait;

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct Netdev {
    #[serde(skip_serializing_if = "Option::is_none")] pub ifindex: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")] pub ifname: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct NetdevInfo {
    #[serde(skip_serializing_if = "Option::is_none")] pub ifindex: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")] pub ifname: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct _InfoReply {
    #[serde(skip_serializing_if = "Option::is_none")] pub info: Option<NetdevInfo>,
}

impl varlink::VarlinkReply for _InfoReply {}

#[derive(Serialize, Deserialize, Debug)]
pub struct _InfoArgs {
    #[serde(skip_serializing_if = "Option::is_none")] pub ifindex: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct _ListReply {
    #[serde(skip_serializing_if = "Option::is_none")] pub netdevs: Option<Vec<Netdev>>,
}

impl varlink::VarlinkReply for _ListReply {}

#[derive(Serialize, Deserialize, Debug)]
pub struct _ListArgs {}

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct _UnknownErrorArgs {
    #[serde(skip_serializing_if = "Option::is_none")] pub text: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Default)]
pub struct _UnknownNetworkIfIndexArgs {
    #[serde(skip_serializing_if = "Option::is_none")] pub ifindex: Option<i64>,
}

pub trait _CallErr: varlink::CallTrait {
    fn reply_unknown_error(&mut self, text: Option<String>) -> io::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "io.systemd.network.UnknownError".into(),
            Some(serde_json::to_value(_UnknownErrorArgs { text }).unwrap()),
        ))
    }
    fn reply_unknown_network_if_index(&mut self, ifindex: Option<i64>) -> io::Result<()> {
        self.reply_struct(varlink::Reply::error(
            "io.systemd.network.UnknownNetworkIfIndex".into(),
            Some(serde_json::to_value(_UnknownNetworkIfIndexArgs { ifindex }).unwrap()),
        ))
    }
}

impl<'a> _CallErr for varlink::Call<'a> {}

pub enum _Error {
    UnknownError(_UnknownErrorArgs),
    UnknownNetworkIfIndex(_UnknownNetworkIfIndexArgs),
    VarlinkError_(varlink::Error),
    UnknownError_(varlink::Reply),
    IOError_(io::Error),
    JSONError_(serde_json::Error),
}

impl From<varlink::Reply> for _Error {
    fn from(e: varlink::Reply) -> Self {
        if varlink::Error::is_error(&e) {
            return _Error::VarlinkError_(e.into());
        }

        match e {
            varlink::Reply {
                error: Some(ref t), ..
            } if t == "io.systemd.network.UnknownError" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p) {
                        Ok(v) => _Error::UnknownError(v),
                        Err(_) => _Error::UnknownError(_UnknownErrorArgs {
                            ..Default::default()
                        }),
                    },
                    _ => _Error::UnknownError(_UnknownErrorArgs {
                        ..Default::default()
                    }),
                }
            }
            varlink::Reply {
                error: Some(ref t), ..
            } if t == "io.systemd.network.UnknownNetworkIfIndex" =>
            {
                match e {
                    varlink::Reply {
                        parameters: Some(p),
                        ..
                    } => match serde_json::from_value(p) {
                        Ok(v) => _Error::UnknownNetworkIfIndex(v),
                        Err(_) => _Error::UnknownNetworkIfIndex(_UnknownNetworkIfIndexArgs {
                            ..Default::default()
                        }),
                    },
                    _ => _Error::UnknownNetworkIfIndex(_UnknownNetworkIfIndexArgs {
                        ..Default::default()
                    }),
                }
            }
            _ => return _Error::UnknownError_(e),
        }
    }
}

impl From<io::Error> for _Error {
    fn from(e: io::Error) -> Self {
        _Error::IOError_(e)
    }
}

impl From<serde_json::Error> for _Error {
    fn from(e: serde_json::Error) -> Self {
        use serde_json::error::Category;
        match e.classify() {
            Category::Io => _Error::IOError_(e.into()),
            _ => _Error::JSONError_(e),
        }
    }
}

impl From<_Error> for io::Error {
    fn from(e: _Error) -> Self {
        match e {
            _Error::UnknownError(e) => io::Error::new(
                io::ErrorKind::Other,
                format!(
                    "io.systemd.network.UnknownError: '{}'",
                    serde_json::to_string_pretty(&e).unwrap()
                ),
            ),
            _Error::UnknownNetworkIfIndex(e) => io::Error::new(
                io::ErrorKind::Other,
                format!(
                    "io.systemd.network.UnknownNetworkIfIndex: '{}'",
                    serde_json::to_string_pretty(&e).unwrap()
                ),
            ),
            _Error::VarlinkError_(e) => e.into(),
            _Error::IOError_(e) => e,
            _Error::JSONError_(e) => e.into(),
            _Error::UnknownError_(e) => io::Error::new(
                io::ErrorKind::Other,
                format!(
                    "unknown varlink error: {}",
                    serde_json::to_string_pretty(&e).unwrap()
                ),
            ),
        }
    }
}
pub trait _CallInfo: _CallErr {
    fn reply(&mut self, info: Option<NetdevInfo>) -> io::Result<()> {
        self.reply_struct(_InfoReply { info }.into())
    }
}

impl<'a> _CallInfo for varlink::Call<'a> {}

pub trait _CallList: _CallErr {
    fn reply(&mut self, netdevs: Option<Vec<Netdev>>) -> io::Result<()> {
        self.reply_struct(_ListReply { netdevs }.into())
    }
}

impl<'a> _CallList for varlink::Call<'a> {}

pub trait VarlinkInterface {
    fn info(&self, call: &mut _CallInfo, ifindex: Option<i64>) -> io::Result<()>;
    fn list(&self, call: &mut _CallList) -> io::Result<()>;
    fn call_upgraded(&self, _call: &mut varlink::Call) -> io::Result<()> {
        Ok(())
    }
}

pub trait VarlinkClientInterface {
    fn info(
        &mut self,
        ifindex: Option<i64>,
    ) -> io::Result<varlink::MethodCall<_InfoArgs, _InfoReply, _Error>>;
    fn list(&mut self) -> io::Result<varlink::MethodCall<_ListArgs, _ListReply, _Error>>;
}

pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}

impl VarlinkClient {
    pub fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        VarlinkClient { connection }
    }
}

impl VarlinkClientInterface for VarlinkClient {
    fn info(
        &mut self,
        ifindex: Option<i64>,
    ) -> io::Result<varlink::MethodCall<_InfoArgs, _InfoReply, _Error>> {
        varlink::MethodCall::<_InfoArgs, _InfoReply, _Error>::call(
            self.connection.clone(),
            "io.systemd.network.Info".into(),
            _InfoArgs { ifindex },
        )
    }
    fn list(&mut self) -> io::Result<varlink::MethodCall<_ListArgs, _ListReply, _Error>> {
        varlink::MethodCall::<_ListArgs, _ListReply, _Error>::call(
            self.connection.clone(),
            "io.systemd.network.List".into(),
            _ListArgs {},
        )
    }
}

pub struct _InterfaceProxy {
    inner: Box<VarlinkInterface + Send + Sync>,
}

pub fn new(inner: Box<VarlinkInterface + Send + Sync>) -> _InterfaceProxy {
    _InterfaceProxy { inner }
}

impl varlink::Interface for _InterfaceProxy {
    fn get_description(&self) -> &'static str {
        r#"
# Provides information about network state
#
interface io.systemd.network

type NetdevInfo (
  ifindex: int,
  ifname: string
)

type Netdev (
  ifindex: int,
  ifname: string
)

# Returns information about a network device
method Info(ifindex: int) -> (info: NetdevInfo)

# Lists all network devices
method List() -> (netdevs: Netdev[])

error UnknownNetworkIfIndex (ifindex: int)
error UnknownError (text: string)
"#
    }

    fn get_name(&self) -> &'static str {
        "io.systemd.network"
    }

    fn call_upgraded(&self, call: &mut varlink::Call) -> io::Result<()> {
        self.inner.call_upgraded(call)
    }

    fn call(&self, call: &mut varlink::Call) -> io::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "io.systemd.network.Info" => {
                if let Some(args) = req.parameters.clone() {
                    let args: _InfoArgs = serde_json::from_value(args)?;
                    return self.inner.info(call as &mut _CallInfo, args.ifindex);
                } else {
                    return call.reply_invalid_parameter(None);
                }
            }
            "io.systemd.network.List" => {
                return self.inner.list(call as &mut _CallList);
            }

            m => {
                return call.reply_method_not_found(Some(String::from(m)));
            }
        }
    }
}
